name: Build and Push to ECR

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-1 # Your AWS region
      REPO_NAME: ${{ github.repository }} # Uses the GitHub repo name (owner/repo)
      IMAGE_TAG: ${{ github.sha }} # Unique tag using the commit SHA

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract Repository Name
        run: |
          # Extract only the repository name (ignore owner)
          REPO_NAME=$(echo "${REPO_NAME}" | cut -d'/' -f2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          # Get AWS Account ID
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          # Define ECR image URI
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

          # Build and tag image with commit SHA
          docker build -t $IMAGE_URI:$IMAGE_TAG .

          # Push image to ECR with the commit SHA tag
          docker push $IMAGE_URI:$IMAGE_TAG

          # Optionally, tag as 'latest' for easy reference
          #docker tag $IMAGE_URI:$IMAGE_TAG $IMAGE_URI:latest
          #docker push $IMAGE_URI:latest
